DROP DATABASE IF EXISTS KG_DB;
CREATE DATABASE KG_DB;

USE KG_DB;

CREATE TABLE USERS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  LAST_NAME VARCHAR(255),
  FIRST_NAME VARCHAR(255),
  PASSWORD_HASH VARCHAR(64),
  USERNAME VARCHAR(255),
  EMAIL_ADDRESS VARCHAR(255),
  ADMIN_MODE TINYINT(1)
);

CREATE TABLE PASSWORDS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  PWORD VARCHAR(255),
  GROUPS VARCHAR(255),
  USER INT,
  CLEARLY_READABLE TINYINT(1) DEFAULT 0
);

CREATE TABLE GROUPS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  GROUP_NAME VARCHAR(255) NOT NULL,
  GROUP_MANAGER INT,
  MEMBERS VARCHAR(255)
);

CREATE TABLE CONFIG(
  ID INT PRIMARY KEY
);

ALTER TABLE PASSWORDS
ADD FOREIGN KEY (USER) REFERENCES USERS(ID);

ALTER TABLE GROUPS
ADD FOREIGN KEY (GROUP_MANAGER) REFERENCES USERS(ID);

INSERT INTO USERS(LAST_NAME,FIRST_NAME,PASSWORD_HASH,USERNAME,EMAIL_ADDRESS,ADMIN_MODE) VALUES ("admin","admin","b03ddf3ca2e714a6548e7495e2a03f5e824eaac9837cd7f159c67b90fb4b7342","admin","oupsi@oupsi.fr",1);
