DROP DATABASE IF EXISTS KG_DB;
CREATE DATABASE KG_DB;

USE KG_DB;

CREATE TABLE USER(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  LAST_NAME VARCHAR(255),
  FIRST_NAME VARCHAR(255),
  PASSWORD_HASH VARCHAR(64),
  USERNAME VARCHAR(255),
  ADMIN_MODE TINYINT(1)
)

CREATE TABLE PASSWORD_REGISTRY(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ENCRYPTED_PASSWORD VARCHAR(255),
  GROUPS VARCHAR(255),
  USER INT,
  CLEARLY_READABLE TINYINT(1) DEFAULT=0;
)

CREATE TABLE GROUPS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  GROUP_NAME VARCHAR(255) NOT NULL,
  GROUP_MANAGER INT
)

CREATE TABLE CONFIG(
  ID INT PRIMARY KEY,
)

ALTER TABLE PASSWORD_REGISTRY
ADD FOREIGN KEY (USER) REFERENCES USER(ID);

ALTER TABLE GROUPS
ADD FOREIGN KEY (GROUP_MANAGER) REFERENCES USER(ID)